use std::io::{self, Write};
use std::path::Path;

use super::*;

fn write_u8(w: &mut impl Write, v: u8) -> io::Result<()> {
    w.write_all(&[v])
}

fn write_u16(w: &mut impl Write, v: u16) -> io::Result<()> {
    w.write_all(&v.to_be_bytes())
}

fn write_i32(w: &mut impl Write, v: i32) -> io::Result<()> {
    w.write_all(&v.to_be_bytes())
}

fn write_string(w: &mut impl Write, s: &str) -> io::Result<()> {
    let bytes = s.as_bytes();
    write_u16(w, bytes.len() as u16)?;
    w.write_all(bytes)
}

/// Writes `servers.dat` back out. Only `name`/`ip` are preserved — this is
/// the launcher's own CRUD, not a full NBT round-trip, so icon/acceptTextures
/// fields Minecraft would have written are dropped and get regenerated by
/// the game itself the next time it connects.
pub fn write_servers(path: &Path, servers: &[ServerEntry]) -> io::Result<()> {
    let mut buf: Vec<u8> = Vec::new();
    write_u8(&mut buf, TAG_COMPOUND)?;
    write_string(&mut buf, "")?;

    write_u8(&mut buf, TAG_LIST)?;
    write_string(&mut buf, "servers")?;
    write_u8(&mut buf, TAG_COMPOUND)?;
    write_i32(&mut buf, servers.len() as i32)?;
    for server in servers {
        write_u8(&mut buf, TAG_STRING)?;
        write_string(&mut buf, "name")?;
        write_string(&mut buf, &server.name)?;

        write_u8(&mut buf, TAG_STRING)?;
        write_string(&mut buf, "ip")?;
        write_string(&mut buf, &server.ip)?;

        write_u8(&mut buf, TAG_END)?;
    }

    write_u8(&mut buf, TAG_END)?; // end root compound

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, buf)
}
