import {
  Anchor,
  Box,
  Building,
  Bug,
  Castle,
  CircleDot,
  Compass,
  Crosshair,
  Diamond,
  Egg,
  Factory,
  Fish,
  Flame,
  Flag,
  Gem,
  Globe,
  Heart,
  Home,
  Landmark,
  Locate,
  MapPin,
  Moon,
  Mountain,
  Navigation,
  Pickaxe,
  Pin,
  Shield,
  Ship,
  Snowflake,
  Star,
  Sun,
  Sword,
  Target,
  Tent,
  TowerControl,
  TreePine,
  Trees,
  Warehouse,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
export const WAYPOINT_ICONS: {
  name: string
  icon: LucideIcon
}[] = [
  { name: 'MapPin', icon: MapPin },
  { name: 'Home', icon: Home },
  { name: 'Building', icon: Building },
  { name: 'Castle', icon: Castle },
  { name: 'TowerControl', icon: TowerControl },
  { name: 'Landmark', icon: Landmark },
  { name: 'Warehouse', icon: Warehouse },
  { name: 'Factory', icon: Factory },
  { name: 'Flag', icon: Flag },
  { name: 'Pin', icon: Pin },
  { name: 'Locate', icon: Locate },
  { name: 'Navigation', icon: Navigation },
  { name: 'Compass', icon: Compass },
  { name: 'Target', icon: Crosshair },
  { name: 'CircleDot', icon: CircleDot },
  { name: 'Mountain', icon: Mountain },
  { name: 'TreePine', icon: TreePine },
  { name: 'Trees', icon: Trees },
  { name: 'Tent', icon: Tent },
  { name: 'Ship', icon: Ship },
  { name: 'Anchor', icon: Anchor },
  { name: 'Pickaxe', icon: Pickaxe },
  { name: 'Diamond', icon: Diamond },
  { name: 'Gem', icon: Gem },
  { name: 'Star', icon: Star },
  { name: 'Heart', icon: Heart },
  { name: 'Shield', icon: Shield },
  { name: 'Sword', icon: Sword },
  { name: 'Skull', icon: Target },
  { name: 'Globe', icon: Globe },
  { name: 'Box', icon: Box },
  { name: 'Flame', icon: Flame },
  { name: 'Snowflake', icon: Snowflake },
  { name: 'Sun', icon: Sun },
  { name: 'Moon', icon: Moon },
  { name: 'Bug', icon: Bug },
  { name: 'Fish', icon: Fish },
  { name: 'Egg', icon: Egg },
]
